### ISSUE TITLE
How to get it running without using a specific Inventory file?

### ISSUE THREAD

**Issue by madhurranjan** [defunctzombie/ansible-coreos-bootstrap#18]
Hi,

I've found your module very useful. However, the one thing that is troubling me right now is how can I run this without using the inventory file ? I tried something like : role : rolename , ansible_python_interpreter="PATH=/home/core/bin:$PATH python" but it fails in the step where its trying to setup pip. Have you run it without an inventory file ? How do I do that?
Thanks.

**Comment by shufo** [comment]
@madhurranjan 
Same problem here.
I tried using set_fact module to set `ansible_python_interapter` in `ansible-coreos-bootstrap/task/main.yml`.
Like this

```
- name: set ansible fact
  set_fact: ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
```

then bootstrap properly worked without using inventory.

**Comment by madhurranjan** [comment]
Thanks @shufo. I'll keep that in mind. I got over it by using dynamic inventory and having the ansible_python_interpreter set as part of that.
