### ISSUE TITLE
Getting "failed to download the file: HTTP Error 403: Forbidden" error on download

### ISSUE THREAD

**Issue by jl-montes** [defunctzombie/ansible-coreos-bootstrap#26]
Hi team,

I've tried running the bootstrap.yml from a home network workstation, no issues
Tried the same from a work/office workstation and get a 403 forbidden error for one of the components. Has anyone seen this kind of error/issue before?
I'm able to do a manual wget of https://github.com/defunctzombie/ansible-coreos-bootstrap/archive/master.tar.gz, but ansible gets a 403 error.

Below is a -vvvv output 

/ansible-work$ ansible-galaxy -vvvv install defunctzombie.coreos-bootstrap --ignore-errors
Using /etc/ansible/ansible.cfg as config file
Opened /home/jmontes/.ansible_galaxy
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
Installing role defunctzombie.coreos-bootstrap
Opened /home/jmontes/.ansible_galaxy
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'coreos-bootstrap', owned by defunctzombie
https://galaxy.ansible.com/api/v1/roles/?owner__username=defunctzombie&name=coreos-bootstrap
https://galaxy.ansible.com/api/v1/roles/1657/versions/?page_size=50
- downloading role from https://github.com/defunctzombie/ansible-coreos-bootstrap/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 403: Forbidden

 [WARNING]: - defunctzombie.coreos-bootstrap was NOT installed successfully.

**Comment by defunctzombie** [comment]
Hm, maybe a transient error since the repo is public. Gonna close cause it seems like a one time thing.

**Comment by Rakaim** [comment]
If something works on your personal machine and not on a corporate network, it's not the Github owner's issue. Seek to understand the infrastructure you're working behind. You're probably facing a proxy or firewall issue.
